/**
 * Bocla - audio.h
 * Audio output subsystem for the Bocla synthesizer.
 * Supports I2S and PWM audio output using RP2040 PIO and DMA.
 * (c) 2024 Luis Enrique Garcia Ontanon
 * See LICENSE.txt for license details.
 */

/**
 * @file audio.h
 * @brief Audio output subsystem for the Bocla synthesizer.
 * Supports I2S and PWM audio output using RP2040 PIO and DMA.
 * Provides a simple API for enqueuing audio buffers for playback and handling underflow events
 *
 * The audio subsystem is designed to be efficient and suitable for real-time audio processing on a microcontroller. It uses a queue-based system to manage audio buffers, allowing the main application to enqueue audio data without blocking. The subsystem handles the low-level details of configuring the PIO for I2S or PWM output, setting up DMA transfers, and managing buffer underflows.
 * The API includes functions for initializing the audio output, enqueuing audio buffers, and
 */
#ifndef AUDIO_H
#define AUDIO_H

#include "cfg.h"

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "hardware/pio.h"

// Import the PIO header generated by CMake
#include "audio.pio.h"

// Max queued buffers before audio_enqueue returns false
#ifndef AUDIO_QUEUE_DEPTH
#define AUDIO_QUEUE_DEPTH 16
#endif

#ifndef AUDIO_UNDERFLOW_TRIGGER_LEVEL
#define AUDIO_UNDERFLOW_TRIGGER_LEVEL 1
#endif

typedef void (*audio_underflow_cb_t)(void *user_data);

// Audio chunk structure for queueing
typedef struct
{
    const int16_t *samples; // Pointer to Stereo Interleaved data (L, R, L, R...)
    size_t len;             // Count of int16_t elements (NOT bytes, NOT frames)
} audio_chunk_t;

/**
 * @brief Configure I2S PIO and DMA.
 *
 * @param pio The PIO instance (pio0/pio1)
 * @param sm The State Machine index
 * @param pin_data The DIN pin
 * @param pin_bclk The BCLK pin (LRC must be pin_bclk + 1)
 * @param sample_rate Audio frequency (e.g., 44100, 48000)
 */
void audio_i2s_init(PIO pio, uint sm, uint pin_data, uint pin_bclk, uint32_t sample_rate);

/**
 * @brief Configure the pwm audio subsystem (PIO + DMA).
 * @param pio The PIO instance (pio0/pio1)
 * @param sm The State Machine index
 * @param l_pin The L pin
 * @param r_pin The R pin
 * @param sample_rate Audio frequency (e.g., 44100, 48000)
 */
void audio_pwm_init(PIO pio, uint sm, uint l_pin, uint r_pin, uint32_t sample_rate);

/**
 * @brief Push a buffer into the playback queue.
 * @param samples Pointer to the data. MUST remain valid until played.
 * @param len Total number of int16 samples in the buffer.
 * @return true if queued, false if queue is full.
 */
bool audio_enqueue(const int16_t *samples, size_t len);

/**
 * @brief Register a callback for underflow events.
 * The callback is called when the audio buffer underruns (i.e., runs out of data).
 * This can be used to trigger visual feedback or attempt to recover.
 * @param cb Function to call on underflow.
 * @param user_data Pointer to pass to the callback.
 * @return true if the callback was registered successfully, false otherwise.
 */
bool audio_register_underflow_callback(audio_underflow_cb_t cb, void *user_data);

/**
 * @brief Get the underflow trigger threshold (in samples) at which the underflow callback will be triggered.
 * @return The number of samples at which underflow is triggered.
 */
size_t audio_get_underflow_trigger_level();

/**
 * @brief Get the current underflow callback and user data.
 * @param user_data_out Output parameter for the user data pointer.
 * @return the callback if registered, NULL if no callback is set.
 */
audio_underflow_cb_t audio_get_underflow_callback(void **user_data_out);

/**
 * @brief Set the underflow trigger threshold (in samples) at which the underflow callback will be triggered.
 * @param level The number of samples at which to trigger underflow. Default is 0 (trigger on actual underflow).
 */
void audio_set_underflow_trigger_level(size_t level);

/**
 * @brief Get the current queue contents for debugging.
 * @param out_chunks Output array to fill with current queue state. Must have space for at least max_chunks elements.
 * @param max_chunks Maximum number of chunks to write to out_chunks (should be >= audio_queue_depth()).
 * @return The actual number of chunks written to out_chunks.
 */
size_t audio_queue(audio_chunk_t *out_chunks, size_t max_chunks);

/**
 * @brief Get the current queue depth.
 * @return The number of buffers currently queued for playback.
 */
inline static size_t audio_queue_depth(void)
{
    return audio_queue(NULL, 0); // Call with NULL to just get the count
}

/**
 * @brief Check if the queue is active.
 *
 * @param current_buffer Optional output parameter to get the currently playing buffer pointer
 * @return The offset of the currently playing buffer in the queue, or NULL if idle.
 * Note: This is not the raw pointer, but an index or identifier you can use to
 */

const int16_t *audio_is_playing(void);

#endif
