/**
 * Bocla - audio.c
 * Audio output driver for the Bocla synthesizer on RP2040.
 * Supports both PWM and I2S output using PIO and DMA.
 * (c) 2024 Luis Enrique Garcia Ontanon
 * See LICENSE.txt for license details.
 */
#include "audio.h"
#include "pico/stdlib.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/clocks.h"
#include "hardware/sync.h"

// Import the PIO header generated by CMake
#include "audio.pio.h"

typedef struct
{
    audio_chunk_t queue[AUDIO_QUEUE_DEPTH];
    uint8_t head;
    uint8_t tail;
    const int16_t *current_buffer; // Tracks the currently playing ptr
    bool active;
    PIO pio;
    uint sm;
    int dma_chan;
} audio_ctx_t;

static volatile audio_ctx_t ctx;

// --- Internal Helper: Next Buffer ---
static bool _load_next_buffer()
{
    if (ctx.head == ctx.tail)
    {
        ctx.active = false;
        ctx.current_buffer = NULL; // Idle
        return false;              // Queue empty
    }

    // Peek at the tail
    audio_chunk_t *chunk = (audio_chunk_t *)&ctx.queue[ctx.tail];

    // Reconfigure and fire DMA
    dma_channel_set_read_addr(ctx.dma_chan, chunk->samples, false);
    dma_channel_set_trans_count(ctx.dma_chan, chunk->len / 2, true); // /2 because 32-bit transfers (Stereo Pair)

    // Update tracking
    ctx.current_buffer = chunk->samples;

    // Advance tail
    ctx.tail = (ctx.tail + 1) % AUDIO_QUEUE_DEPTH;
    ctx.active = true;
    return true;
}

// --- DMA Interrupt Handler ---
void __not_in_flash_func(audio_dma_handler)()
{
    // Clear the interrupt request
    dma_hw->ints0 = 1u << ctx.dma_chan;

    // Try to load the next chunk immediately
    if (!_load_next_buffer())
    {
        // Underflow / End of Stream.
        // ctx.current_buffer is set to NULL in _load_next_buffer
    }
}

// --- Public API ---
void audio_pwm_init(PIO pio, uint sm, uint l_pin, uint r_pin, uint32_t sample_rate)
{
    // TO DO: Implement PWM-based audio output using PIO and DMA. This is more complex and may require a different PIO program.
}

void audio_i2s_init(PIO pio, uint sm, uint pin_data, uint pin_bclk, uint32_t sample_rate)
{
    ctx.pio = pio;
    ctx.sm = sm;
    ctx.head = 0;
    ctx.tail = 0;
    ctx.active = false;
    ctx.current_buffer = NULL;

    // 1. Configure PIO (Assumes i2s_out_program is loaded in main)
    uint offset = pio_add_program(pio, &i2s_out_program);
    i2s_out_program_init(pio, sm, offset, pin_data, pin_bclk);

    // Adjust clock divider for exact sample rate
    // Freq = sample_rate * 32 bits * 2 (LR)
    uint32_t system_clock = clock_get_hz(clk_sys);
    uint32_t bit_clock = sample_rate * 32 * 2;
    float div = (float)system_clock / bit_clock;
    pio_sm_set_clkdiv(pio, sm, div);

    // 2. Configure DMA
    ctx.dma_chan = dma_claim_unused_channel(true);
    dma_channel_config c = dma_channel_get_default_config(ctx.dma_chan);

    channel_config_set_transfer_data_size(&c, DMA_SIZE_32); // Move 2x 16-bit samples (Left+Right) at once
    channel_config_set_read_increment(&c, true);
    channel_config_set_write_increment(&c, false);
    channel_config_set_dreq(&c, pio_get_dreq(pio, sm, true)); // TX FIFO request

    dma_channel_configure(
        ctx.dma_chan,
        &c,
        &pio->txf[sm], // Write to PIO FIFO
        NULL,          // Read from... (set later)
        0,             // Count... (set later)
        false          // Don't start
    );

    // 3. Enable Interrupts
    dma_channel_set_irq0_enabled(ctx.dma_chan, true);
    irq_set_exclusive_handler(DMA_IRQ_0, audio_dma_handler);
    irq_set_enabled(DMA_IRQ_0, true);
}

bool audio_enqueue(const int16_t *samples, size_t len)
{
    // Prevent ISR from messing with head while we write
    uint32_t save = save_and_disable_interrupts();

    uint8_t next_head = (ctx.head + 1) % AUDIO_QUEUE_DEPTH;

    if (next_head == ctx.tail)
    {
        restore_interrupts(save);
        return false; // Queue Full
    }

    ctx.queue[ctx.head].samples = samples;
    ctx.queue[ctx.head].len = len;
    ctx.head = next_head;

    // If DMA is idle, kickstart it immediately
    if (!ctx.active)
    {
        _load_next_buffer();
    }

    restore_interrupts(save);
    return true;
}

const int16_t *audio_is_playing(void)
{
    // Atomic read is fine here
    return ctx.current_buffer;
}

size_t audio_queue(audio_chunk_t *out_chunks, size_t max_chunks)
{
    size_t count = 0;
    uint8_t idx = ctx.tail;

    while (idx != ctx.head && count < max_chunks)
    {
        if (out_chunks)
        {
            out_chunks[count] = ctx.queue[idx];
        }
        idx = (idx + 1) % AUDIO_QUEUE_DEPTH;
        count++;
    }

    return count;
}

static audio_underflow_cb_t underflow_cb = NULL;
static void *underflow_user_data = NULL;
static int16_t underflow_trigger_level = AUDIO_UNDERFLOW_TRIGGER_LEVEL;

void audio_check_underflow()
{
    if (ctx.active && audio_queue_depth() <= underflow_trigger_level)
    {
        if (underflow_cb)
        {
            underflow_cb(underflow_user_data);
        }
    }
}

void audio_set_underflow_trigger_level(size_t level)
{
    underflow_trigger_level = level;
}

size_t audio_get_underflow_trigger_level()
{
    return underflow_trigger_level;
}

bool audio_register_underflow_callback(audio_underflow_cb_t cb, void *user_data)
{

    underflow_cb = cb;
    underflow_user_data = user_data;

    return true;
}

audio_underflow_cb_t audio_get_underflow_callback(void **user_data_out)
{
    if (user_data_out)
    {
        *user_data_out = underflow_user_data;
    }
    return underflow_cb;
}
